<?php
require "vendor/autoload.php";
namespace integracionCOntinua\modelo\saludo;
use integracionCOntinua\modelo\saludo;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-22 at 12:45:06.
 */
class saludoTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var saludo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new saludo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * 
     */
    public function testSetSaludo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @dataProvider proveedorFormatSaludo
     */
    public function testFormatSaludo($saludo, $saludoEsperado) {
       $this->object->setSaludo($saludo);
       $saludoObtenido = $this->object->formatSaludo();
       $this->assertEquals($saludoObtenido,$saludoEsperado);
    }
    
    public function proveedorFormatSaludo(){
        return [
          "Saludo 1" => ["Hola", "EL mensaje es: hola"],
          "Saludo 2" => ["Hola", "EL mensaje es: hola"],
        ];
    }

}
